# Replace “File” with the name of your Java file, sans extension. For example, if you
# were working with a Java file called, Assignment2.java, then replace “File” with
# “Assignment2”.
filename = File

all: compile run

compile:
	javac $(filename).java

run:
	java $(filename)

clean:
	rm $(filename).class
